{
 "title": "P&F Performance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(apiserver_request_total{apiserver=\"kube-apiserver\"}, instance)"
   },
   {
    "name": "resource",
    "label": "resource",
    "query": "label_values(apiserver_request_duration_seconds_bucket, resource)"
   },
   {
    "name": "code",
    "label": "code",
    "query": "label_values(apiserver_request_total,code)"
   },
   {
    "name": "verb",
    "label": "verb",
    "query": "label_values(apiserver_request_total,verb)"
   },
   { "name": "flow_schema", "label": "flow-schema", "query": "label_values(flow_schema)" },
   { "name": "priority_level", "label": "priority-level", "query": "label_values(priority_level)" },
   { "name": "interval", "label": "interval", "query": "2m,5m" }
  ]
 },
 "panels": [
  {
   "title": "kube-apiserver status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{apiserver=\"kube-apiserver\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Kube-apiserver CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"kube-apiserver\",name!=\"\",namespace=~\"openshift-kube-apiserver\"}[$interval])) by (pod) * 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Kube-apiserver RSS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{container=\"kube-apiserver\",name!=\"\",namespace=~\"openshift-kube-apiserver\"}) by (pod)",
     "legendFormat": "{{ pod }}: {{ container }}"
    }
   ]
  },
  {
   "title": "request rate - by instance & verb",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{apiserver=\"kube-apiserver\",instance=~\"$instance\",resource=~\"$resource\",code=~\"$code\",verb=~\"$verb\"}[$interval])) by(instance, verb, resource, code) > 0",
     "legendFormat": "{{ instance }} {{ verb }} {{resource}}"
    }
   ]
  },
  {
   "title": "request rate - by instance & resource",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{apiserver=\"kube-apiserver\",instance=~\"$instance\",resource=~\"$resource\",code=~\"$code\",verb=~\"$verb\"}[$interval])) by(instance, resource,code) > 0",
     "legendFormat": "{{ instance }} {{ resource }}"
    }
   ]
  },
  {
   "title": "Requests status rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{apiserver=~\"kube-apiserver\",instance=~\"$instance\",resource=~\"$resource\",verb=~\"$verb\",code=~\"$code\"}[$interval])) by(instance,code, resource)",
     "legendFormat": "{{instance}}: {{code}}"
    }
   ]
  },
  {
   "title": "Registered watchers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Watchers" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_registered_watchers{apiserver=\"kube-apiserver\"}) by (instance,apiserver)",
     "legendFormat": "{{apiserver}} {{instance}}"
    }
   ]
  },
  {
   "title": "request duration - 99th quantile by instance-resource",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{apiserver=~\"kube-apiserver\",instance=~\"$instance\",resource=~\"$resource\",subresource!=\"log\",verb!~\"WATCH|WATCHLIST|PROXY\"}[$interval])) by(instance,resource,le))",
     "legendFormat": "{{instance}}:{{resource}}"
    }
   ]
  },
  {
   "title": "request duration - 99th quantile by instance & verb",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{apiserver=\"kube-apiserver\",instance=~\"$instance\",resource=~\"$resource\",subresource!=\"log\",verb!~\"WATCH|WATCHLIST|PROXY\"}[$interval])) by(instance,verb,le))",
     "legendFormat": "{{instance}}: {{verb}}"
    }
   ]
  },
  {
   "title": "p&f Inqueue requests by request kind",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apiserver_current_inqueue_requests{apiserver=\"kube-apiserver\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}: {{ request_kind }}"
    }
   ]
  },
  {
   "title": "p&f dispatched requests total by flow-schema",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(apiserver_flowcontrol_dispatched_requests_total{instance=~\"$instance\",flow_schema=~\"$flow_schema\"}[$interval])",
     "legendFormat": "{{instance}}: {{flow_schema}}  {{ priority_level}}"
    }
   ]
  },
  {
   "title": "p&f Priority level",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(apiserver_flowcontrol_request_concurrency_limit{}) by (priority_level)",
     "legendFormat": "{{ priority_level }}"
    }
   ]
  },
  {
   "title": "p&f - Concurrent requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_flowcontrol_current_executing_requests{instance=~\"$instance\", flow_schema=~\"$flow_schema\", apiserver=\"kube-apiserver\", priority_level=~\"$priority_level\"}) by (instance, priority_level,flow_schema)",
     "legendFormat": "{{instance}}: {{flow_schema}}  {{ priority_level}}"
    }
   ]
  },
  {
   "title": "p&f -Rejected requests by flowSchema and PriorityLevel",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(apiserver_flowcontrol_rejected_requests_total{instance=~\"$instance\",flow_schema=~\"$flow_schema\", priority_level=~\"$priority_level\"}[2m]) > 0",
     "legendFormat": "{{instance}}: {{flow_schema}}  {{ priority_level}}"
    }
   ]
  },
  {
   "title": "p&f Queue wait duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_flowcontrol_request_wait_duration_seconds_bucket{apiserver=\"kube-apiserver\",flow_schema=~\"$flow_schema\", priority_level=~\"$priority_level\", execute=\"true\"}[2m])) by(instance, flow_schema, priority_level, le))",
     "legendFormat": "{{instance}}: {{flow_schema}}  {{ priority_level}}"
    }
   ]
  },
  {
   "title": "p&f - Current inqueue requests by priority_level and flow_schema",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_flowcontrol_current_inqueue_requests{instance=~\"$instance\",priority_level=~\"$priority_level\", flow_schema=~\"$flow_schema\"}) by (instance, flow_schema, priority_level) > 0",
     "legendFormat": "{{instance}}: {{flow_schema}}  {{ priority_level}}"
    }
   ]
  }
 ]
}