# SECRETS_PER_POD specifies the number of secrets to mount in each pod
{{$SECRETS_PER_POD := 200 }}

---
global:
  writeToFile: false
  metricsDirectory: collected-metrics
  indexerConfig:
    enabled: false

jobs:
  - name: apf-watch
    namespace: apf-watch
    jobIterations: 150
    qps: 20
    burst: 20
    namespacedIterations: true
    cleanup: true
    podWait: false
    waitFor: []
    waitWhenFinished: true
    objects:

      - objectTemplate: templates/pod.yml
        replicas: 10
        inputVars:
          SECRETS_PER_POD: {{ $SECRETS_PER_POD }}

      - objectTemplate: templates/secret.yml
        replicas: {{ $SECRETS_PER_POD }}
